### ISSUE TITLE
keygen 

### ISSUE THREAD

**Issue by ghost** [ImVexed/NotALicensingPlatform#4]
Thanks for the Project! Kinda new on this, any idea how to fix this? 
`C:\WINDOWS\system32>docker exec nalp nalp --genkey "6 months"

[23:46:12] No DB provider specified! See --help`

**Comment by ImVexed** [comment]
When generating a key, nalp still needs to know where to store the key. All you have to do is provide a database like `--sqlite /data`.

I also seemed to have missed the fact that in the Dockerfile I specified the data provider using `CMD` https://github.com/ImVexed/NotALicensingPlatform/blob/master/Server/Dockerfile#L16 but this is overwritten when `exec`ing or providing a custom command so I've now shifted it into `ENTRYPOINT`.

So that would be why it's not working out of the box, sorry!

**Comment by ghost** [comment]
Thanks it works! 

Amazing project! 👍

**Comment by ImVexed** [comment]
Fixed by https://github.com/ImVexed/NotALicensingPlatform/commit/4e11fe3137b6459d29a6cc5241b4dfc9a3d35c1a

**Comment by ImVexed** [comment]
After a bit more investigation, `docker exec` completely ignores `ENTRYPOINT` so https://github.com/ImVexed/NotALicensingPlatform/commit/4e11fe3137b6459d29a6cc5241b4dfc9a3d35c1a is not a fix, the readme has been updated to reflect the need to specify a data provider
